name = "Skymod"
author = "Vin"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b43f0374d3386132fceb04f4a757c327c702716bd61a60cdad051b1f8f40994"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
