name = "Skymod"
author = "Vin"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20eda2136d2e5b8a4214df62c3a7284869f3b8373683ee6b09c0a04f8a37d763"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
